 server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        # 只处理 /admin
        location /vfc-ai-api/ {
            proxy_pass https://api.coze.cn/;
            proxy_set_header Authorization "Bearer COZE_TOKEN";
        }
}