 server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        # 只处理 /admin
        location /vfc-ai-api/ {
            proxy_pass https://api.coze.cn/;
            proxy_set_header Authorization "Bearer pat_QOUuedL6E93SXWER1jBx1he11QemSZ1Sz6k1M5hng966tCdf211ri7iZC0Zwp1wS";
        }
}