export { default as FormRender } from './FormRender.vue'
export { default as FormItem } from './FormItem.vue'
export { default as FormItemRender } from './FormItemRender.vue'
// export { default as IconRender } from './IconRender.vue'
export { default as Disabled } from './Disabled.vue'
export { default as FormDesign } from './FormDesign/index.vue'
export { default as CanvasWrapper } from './FormDesign/Center/Canvas/CanvasWrapper.vue'
export { default as DefaultCanvasWrapper } from './DefaultCanvasWrapper.vue'
export { default as CodeHighLight } from './CodeHighLight.vue'
